### ISSUE TITLE
Test how "days" parameter works

### ISSUE THREAD

**Issue by omerbensaadon** [loganpowell/granicus#5]
If you use parameters "days" and "start_date" does it return an array of results, one for each day up unto today?

**Comment by omerbensaadon** [comment]
Okay, updating in this format. 

Use case: We want to be able to pull data for the past few "Days" in a week. For example, if we wanted to create a stacked bar-chart like this: 
<img width="924" alt="Screen Shot 2019-03-30 at 1 48 17 PM" src="https://user-images.githubusercontent.com/16281246/55279757-877a1900-52f2-11e9-94a5-cf252d1f9cb8.png">

We would need to pull data for each day of that week, which would mean 7 different API calls if we were using the `start_date` and 'end_date` parameters. The calls would look something like this for each and every day of that week: 

`https://api.govdelivery.com/api/v2/accounts/<account id>/reports/subscriber_activity/summary?start_date=<start_date>&end_date=<end_date>` x7 for each day of the week

govDelivery also has a parameter called `days` which "May be combined with end_date to get the X days ending in end_date;" according to their documentation. 

**Given this fact, I'm curious if the `days` parameter returns a JSON object with all of the data for each of the days leading up to the `end_date` individually or if it simply subtracts the number of days you pass it from the `end_date` and would be functionally the same running the API call detailed above**

The API Call in question would look like this: 
`https://api.govdelivery.com/api/v2/accounts/<account id>/reports/subscriber_activity/summary?end_date=<end_date>&days=7`

**Comment by loganpowell** [comment]
This is a very good way to document a requirement. Very specific.

**Comment by loganpowell** [comment]
Btw, if you want to test out the API there's this easy-to-use tool:

https://www.getpostman.com/

**Comment by loganpowell** [comment]
I've just added a request using the `days` parameter to a team on Postman, which I've invited you to. Look out for an email to your personal

**Comment by omerbensaadon** [comment]
@loganpowell woah, Postman is great! 

Just used it to test this exact use-case and no dice. 

`https://api.govdelivery.com/api/v2/accounts/<account id>/reports/subscriber_activity/summary?end_date=2019-03-31&days=1`

The call above simply subtracts the number of days submitted from the `end_date`. 

In fact, in the "self" portion of the response, it's listed as: 

`/api/v2/accounts/11723/reports/subscriber_activity/summary?end_date=2019-03-31&start_date=2019-03-30`

Huge bummer. this is definitely something we need to bring up with the Granicus API folks. 

`days` parameter ought to return a result for each day.

**Comment by loganpowell** [comment]
If we can get it using dates, it's not a big deal. Let's choose our battles with the Granicus folks. We want them on our team

**Comment by omerbensaadon** [comment]
I'm with you, I'm not raising it as a concern right now. 

But, when we meet with the API team, let's try and have a backlog of feature requests and we can prioritize which ones to bring up. 

My guess is they don't get user feedback as often as they'd like, and we may be able to get a feature added that makes our lives easier.
