### ISSUE TITLE
Questions about keys

### ISSUE THREAD

**Issue by loganpowell** [loganpowell/granicus#6]
We have two functional keys to make API requests:
1. Account ID
2. API key

Do both of these need to be private?

**Comment by loganpowell** [comment]
Currently handling these by making the user supply them in the WDC UI (interactive phase)

**Comment by omerbensaadon** [comment]
I'm going to Reopen just so I can make sure to get clarity from Granicus as to whether or not the Account ID needs to be private and so we can discuss how this impacts user experience. 

Let's discuss on Wednesday (at our soon-to-be-scheduled engineering meeting)

**Comment by omerbensaadon** [comment]
Account-ID is not classified as a sensitive piece of information according to Granicus.
